#!/usr/bin/env bash

if [ ! -z $(which brew) ] && [ "$1" != "-f" ]; then
    echo "brew is already installed"
    echo "Use \"$0 -f\" to force installation."
    exit 1
fi

echo "Info: http://brew.sh"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
