#!/usr/bin/env bash

#sudo ./remove-macports
./install-homebrew
./install-homebrew-cask

for pkg in $(cat essential-cmds.txt); do
    if [ "$(which $pkg)" ]; then
        echo "$pkg is already installed."
    else
        brew install "$pkg"
    fi
done

cask_list="$(brew cask list | tr \\t \\n)"
for pkg in $(cat essential-apps.txt); do
    if [ "$(echo $cask_list | grep $pkg)" ]; then
        echo "$pkg is already installed."
    elif [ "$(ls -1 /Applications | grep -i "$pkg.app")" ]; then
        echo "$pkg exists in /Applications."
    else
        brew cask install "$pkg"
    fi
done

sudo ./install-pip
