#!/usr/bin/env bash

# Is there anything to do?
if [ ! -z $(which php) ] && [ ! -z $(which composer) ] && [ "$1" != "-f" ]; then
    echo "php and composer are already installed." >&2
    echo "Use \"$0 -f\" to force installation." >&2
    exit 0
fi

# Are all of the dependencies available?
if [ -z $(which brew) ]; then
    echo "fatal: Homebrew is not installed." >&2
    echo "visit: http://brew.sh" >&2
    exit 1
fi

echo "See: https://github.com/Homebrew/homebrew-php"
echo "and: https://getcomposer.org/doc/00-intro.md"
brew update
brew upgrade
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php70
brew install composer --ignore-dependencies

exit $?
