#!/usr/bin/env bash

# Install the Python modules needed for scraping web sites.

if [ ! "$(which pip3)" ]; then
    >&2 echo "fatal: pip3 is not installed"
    exit 1
fi

pip3 install beautifulsoup4
pip3 install lxml
pip3 install html5lib
pip3 install requests
