#!/usr/bin/env bash

# Update npm first.
packages=(
    npm
    nodemon
    express-generator
    typescript
    yarn
)

for package in ${packages[@]}; do
    echo "Installing ${package}..."
    npm install -g "$package"
done

npm audit fix

