#!/usr/bin/env bash

install_globally() {
    if [ -z "$1" ]; then
        >&2 echo "usage: $0 <package>"
        return 1
    fi
    npm install -g "$1" | grep -v fund | grep -v '^$'
}

if [ -z "$(which npm)" ]; then
    echo "Installing npm..."
else
    echo "Updating npm..."
fi
install_globally npm

packages=(
    nodemon
    yarn
)

for package in ${packages[@]}; do
    if [ -n "$(which "$package")" ]; then
        echo "$package is already installed."
        continue
    fi
    echo "Installing ${package}..."
    install_globally "$package"
done

./install-node-package express-generator express
./install-node-package typescript tsc

echo "npm audit fix"
npm audit fix | grep -v fund | grep -v '^$'
