#!/usr/bin/env bash
# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

PS1='\t \u@\h:\w \$ '

PATH="$PATH:$HOME/.rvm/bin"
PATH="/usr/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/usr/local/bin:$PATH" # Prioritize Homebrew commands.
PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
PATH="$HOME/Library/Python/3.7/bin:$PATH"
PATH="$HOME/bin:$PATH"
export PATH

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi
source ~/.git-completion.bash

# For compilers to find openblas you may need to set:
export LDFLAGS="-L/usr/local/opt/openblas/lib"
export CPPFLAGS="-I/usr/local/opt/openblas/include"

# For pkg-config to find openblas you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"
