#!/usr/bin/env bash
# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

# Source ~/.bashrc, so we can keep common commands there.
if [ -f ~/.bashrc ]; then 
    source ~/.bashrc 
fi

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export VISUAL=vim
export EDITOR="$VISUAL"

