#!/usr/bin/env bash

if [ "$(which code)" ]; then
    >&2 echo "code is already installed."
    exit 0
fi

if [ $UID -ne 0 ]; then
    echo "fatal: This script must be run as root." >&2
    echo "usage: sudo $0" >&2
    exit 1
fi

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft-archive-keyring.gpg
rm microsoft.gpg
sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

apt-get install apt-transport-https
apt-get update
apt-get install code
