#!/usr/bin/env bash

echo "Info: https://www.debian.org/doc/manuals/debian-kernel-handbook/ch-common-tasks.html"

if [ $UID -ne 0 ]; then
    echo "fatal: This script must be run as root." >&2
    echo "usage: sudo $0" >&2
    exit 1
fi

apt-get -y install build-essential fakeroot devscripts
apt-get -y build-dep linux
#apt-get source linux

echo
echo "Please use:"
echo
echo "    git clone https://salsa.debian.org/kernel-team/linux.git"
echo
echo "to retrieve the latest updates to the kernel source code."
echo
