#!/usr/bin/env bash

#sudo ./remove-macports
./install-homebrew

# Install command line programs.
for pkg in $(cat essential-cmds.txt); do
    if [ "$(which $pkg)" ]; then
        echo "$pkg is already installed."
    else
        brew install "$pkg"
    fi
done

# Install GUI programs.
cask_list="$(brew list --cask | tr \\t \\n)"
for pkg in $(cat essential-apps.txt); do
    if [ "$(echo $cask_list | grep $pkg)" ]; then
        echo "$pkg is already installed."
    elif [ "$(ls -1 /Applications | grep -i "$pkg.app")" ]; then
        echo "$pkg exists in /Applications."
    else
        brew install --cask "$pkg"
    fi
done

./install-homebrew-package mysql@5.7 mysql
./install-homebrew-package rust rustc
./install-homebrew-package tcl-tk tclsh

./install-node-packages
./install-nvm
#./install-python-modules
