#!/usr/bin/env bash

if type brew >/dev/null && [ "$1" != "-f" ]; then
    echo "brew is already installed"
    echo "Use \"$0 -f\" to force installation."
    exit 1
fi

echo "Info: http://brew.sh"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/ben/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
