#!/usr/bin/env bash

alias less="less -FXR"

alias ls="ls -FG" # Decorate and color output
alias ll="ls -l"
alias la="ls -la"

alias megs='du -sm * | sort -nr -k1,1'
alias gigs='du -sm * | sort -nr -k1,1'

if [ "$(which lolcat)" ]; then
    alias fortune="fortune | lolcat"
fi
